

export enum CourtType {
    FIRST_INSTANCE = "FIRST_INSTANCE",
    COMMERCIAL = "COMMERCIAL",
    APPEAL = "APPEAL",
    PROXIMITY = "PROXIMITY",
    ADMINISTRATIVE = "ADMINISTRATIVE",
    CASSATION = "CASSATION",
}